apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: todolist-project
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres  
        volumeMounts:
            - name: postgres-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim  
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: todolist-project
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30101
