apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: todolist-project 
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: rama534s/todolist:1.2
        ports:
        - containerPort: 8080
        env:
         - name: POSTGRES_HOST
           value: postgres
         - name: POSTGRES_PORT
           value: "5432"
         - name: DATABASE_URL
           value: jdbc:postgresql://postgres-service:5432/postgres
         - name: DATABASE_USERNAME
           value: postgres
         - name: DATABASE_PASSWORD
           value: postgres
         
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: todolist-project
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30100